import os
from dotenv import load_dotenv

load_dotenv()

CLEAN_SM_DB_INTERVAL = 3600

TAILSCALE_IP_POLL_TIMEOUT=1200
TAILSCALE_IP_POLL_INTERVAL=3
TAILSCALE_IPS_POLL_CHECK_FREQ=5

TOKEN_EXPIRE_TMP=36000