import os
from dotenv import load_dotenv

load_dotenv()

CLEANER_INTERVAL = 3600

TAILSCALE_IP_POLL_TIMEOUT=1200
TAILSCALE_IP_POLL_INTERVAL=3
TAILSCALE_IPS_POLL_CHECK_FREQ=5

TOKEN_EXPIRE_TMP=36000

GCS_PROOF_TOKENS_FILE = 'rfd/gcs_proof_tokens.txt'
GCS_PROOF_TOKEN_BASE = 3.479

TAILSCALE_API_KEY = os.getenv("TAILSCALE_API_KEY")
TAILNET = os.getenv("TAILNET")